### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by ArnoAnsems** [ArnoAnsems/CatacombGL#11]
Feasibility to be investigated.

Suggested by @alescandy:
https://twitter.com/alescandy/status/1212981522522869760

**Comment by alessioscand** [comment]
Howdy! It's always me, from Twitter. Thank you so much for implementing the RPi support, I've tested it and it works beautifully:
https://twitter.com/alescandy/status/1602370571890823171?t=2RYU9R40ooqwi-Md-O44rA&s=19

**Comment by ArnoAnsems** [comment]
Thanks for the confirmation that RPi support is working, @alessioscand. I will now close this issue.
