### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by ArnoAnsems** [ArnoAnsems/CatacombGL#12]
Feasibility to be investigated.
The current version does work with Wine, as confirmed by [Tricob](http://dhw.wolfenstein3d.com/viewtopic.php?p=107816#107816).

Suggested by:
Dinoaur: https://www.doomworld.com/forum/topic/102331-catacombgl-043-supporting-all-catacomb-3d-games/?page=3&tab=comments#comment-2065494
@StormkeeperGU: https://twitter.com/StormkeeperGU/status/1243293911063433220

**Comment by arrowgent** [comment]
cmake/make is the typical compiling process for linux
i would love a linux version.   wine also worked just fine for me.

complexity of adding cmake and makefiles would be a great learning process for you/the developer

**Comment by ArnoAnsems** [comment]
> cmake/make is the typical compiling process for linux
> i would love a linux version. wine also worked just fine for me.
> 
> complexity of adding cmake and makefiles would be a great learning process for you/the developer
> 
> adding "requirements" aka dependencies
> which versions of GCC and G++ is important.
> building for various historical distros (ie: making sure it compiles correctly for ubuntu 16.04/18.04/etc)
> 
> https://github.com/onqtam/awesome-cmake

Thanks for the pointers, @arrowgent. CMake is a good suggestion. I'm planning to move to cmake, as plenty of high profile source ports seem to use it, like GZDoom. In the background I'm already doing some preparations towards multi-platform support, like removing Windows-specific include files. But the majority of the work will be done after version 1.0.0. The biggest hurdle will probably be that I'm very, very inexperienced with using Linux. I will have to learn how to install a Linux OS and do basic tasks. I'm interested to learn, but it will take some time.

**Comment by stuaxo** [comment]
I tried this on Ubuntu 22.04, and it's complaining about SDL missing when I try and compile, is this something cmake could detect instead ?

**Comment by ArnoAnsems** [comment]
Native Linux support was implemented by @GoGoOtaku and now part of the 0.5.4 release.
