### ISSUE TITLE
ECWolf-like Automap?

### ISSUE THREAD

**Issue by MasterO2** [ArnoAnsems/CatacombGL#25]
Would an automap feature for Catacombs be feasible, akin to how ECWolf implements it for Wolfenstein 3D?  Also, a sub-feature that highlights breakable walls in the levels themselves?

**Comment by ArnoAnsems** [comment]
Thanks, that's an interesting feature suggestion!
The original source code from Catacomb Abyss even contains some functionality in C4_DEBUG.C to draw an overhead map when F10+O is pressed. Unfortunately it doesn't work without recompiling the executable, as by default it is disabled via a compiler flag.

**Comment by MasterO2** [comment]
@ArnoAnsems, thanks for implementing this in [Version 5.0](https://github.com/ArnoAnsems/CatacombGL/releases/tag/v0.5.0-beta).  

Issue is now closed.
