### ISSUE TITLE
CatacombGL Download 

### ISSUE THREAD

**Issue by goldenmob72** [ArnoAnsems/CatacombGL#26]
Where do I download CatacombGL ? I don't see any download, Just the source codes 

![Screenshot_2](https://user-images.githubusercontent.com/40510344/88938371-4fbb1280-d253-11ea-9be7-f1e3bbd3d62f.png)

**Comment by ArnoAnsems** [comment]
The following link should show the zip files with the binaries:
https://github.com/ArnoAnsems/CatacombGL/releases/tag/v0.4.3-beta

**Comment by ArnoAnsems** [comment]
A new version is released:
https://github.com/ArnoAnsems/CatacombGL/releases/tag/v0.5.0-beta
I'm closing this issue now, assuming that downloading works.
