### ISSUE TITLE
Can't find the executable

### ISSUE THREAD

**Issue by MidKnight91939** [ArnoAnsems/CatacombGL#35]

**Comment by ArnoAnsems** [comment]
Hi,
The latest release can be found here: https://github.com/ArnoAnsems/CatacombGL/releases/tag/v0.5.2-beta
Both the x64 and x86 zip files under "assets" should contain these four files: CatacombGL.exe, licenses.zip, readme.txt and SDL2.dll.
Could it be that a virus scanner on your side accidently removed the .exe from the zip file?
