### ISSUE TITLE
Use alternative background color in automap when floor color is black

### ISSUE THREAD

**Issue by ArnoAnsems** [ArnoAnsems/CatacombGL#36]
When the floor color is black, for example in the Dark Forest level, it is difficult to distinct explored from unexplored areas in the automap. A solution can be to use an alternative background color in the automap when floor color is black

Mentioned in this Twitch stream by Mech04:
https://www.twitch.tv/videos/1037978119

**Comment by arrowgent** [comment]
https://github.com/ArnoAnsems/CatacombGL/releases/tag/v0.5.3-beta

seems like this was added here?
`By default the automap has a black background color. However, when the floor color is also black, the automap will now use dark gray as the background color. This helps in making a distinction between explored and unexplored areas. Suggested by Mech4Gaming.`

tested Topdown, Topdown HD (not sure what this does), Isometric, & original Debug.  looks good

**Comment by ArnoAnsems** [comment]
Correct, I added this in version 0.5.3. I'm just a little bit behind in the Github administration. :-)
Thanks for confirming that it works as intended!

The topdown mode uses the 16x16 tiles from the TEDS level editor to visualize the walls on the automap. This resembles the original 320x200 screen resolution.
The topdown HD mode uses the actual 64x64 textures to visualize the walls on the automap. This mode benefits from a higher screen resolution.
