### ISSUE TITLE
Can't find the .exe file

### ISSUE THREAD

**Issue by BoneApart** [ArnoAnsems/CatacombGL#37]
Looked for it seemingly everywhere and didn't find it. Maybe you guys left it out of the folder by accident? Am I not looking for the right file? If you guys could please fix this, that'd be great. Thanks in advance!

**Comment by ArnoAnsems** [comment]
Hi,
The latest release can be found here: https://github.com/ArnoAnsems/CatacombGL/releases/tag/v0.5.2-beta
Both the x64 and x86 zip files under "assets" should contain these four files: CatacombGL.exe, licenses.zip, readme.txt and SDL2.dll.
Could it be that a virus scanner on your side accidently removed the .exe from the zip file?

**Comment by BoneApart** [comment]
Hm, weird. The .exe file didn't show up when I looked it up on the github
page earlier. It does appear to be on the link you sent me, though.

The issue's been resolved. Thanks a lot!
