### ISSUE TITLE
Split help screen bug

### ISSUE THREAD

**Issue by NY00123** [ArnoAnsems/CatacombGL#40]
This has been reproduced in the Adventure Series with CatacombGL 0.5.3.

![Screenshot from 2021-09-05 00-14-09](https://user-images.githubusercontent.com/6780140/132108268-650e5f08-2844-4124-8872-a8e176cc6374.png)

**Comment by ArnoAnsems** [comment]
Oops! I accidently introduced this bug when I added the overscan border. It will be fixed in the next release. Thanks for reporting this!

**Comment by NY00123** [comment]
Confirming as fixed, thanks!
