### ISSUE TITLE
Attempting to leave debug key dialog with Esc leads to the menu

### ISSUE THREAD

**Issue by NY00123** [ArnoAnsems/CatacombGL#41]
Steps for reproducing in Catacomb Abyss:
1. Press on F10+W.
2. Press on Esc.
Instead of removing the dialog, the menu will appear. In order to hide the dialog, you can press on "Enter" after adding no text.

**Comment by ArnoAnsems** [comment]
Thanks for reporting this!
In the next release it will be fixed: pressing esc will close the warp, god or items dialogs without opening the menu.

**Comment by NY00123** [comment]
This is indeed fixed, thanks!
