### ISSUE TITLE
Linux: Check default wine prefix for GOG Catacombs pack

### ISSUE THREAD

**Issue by stuaxo** [ArnoAnsems/CatacombGL#48]
There are probably a few of places the GOG Catacombs Pack could be installed, the default wine prefix is probably a good place to look to start -

`~/.wine/dosdevices/c:/GOG Games/Catacombs Pack`

**Comment by ArnoAnsems** [comment]
Thank you for this great suggestion!
I implemented it via [this commit](https://github.com/ArnoAnsems/CatacombGL/commit/6e9a7c45c31fdced634206c564e63c50b66a3be7).
