### ISSUE TITLE
Support original 320x200 screen resolution

### ISSUE THREAD

**Issue by ArnoAnsems** [ArnoAnsems/CatacombGL#5]
Support or simulate the original 320x200 screen resolution, possibly in combination with widescreen.

Suggested by Dinoaur:
https://www.doomworld.com/forum/topic/102331-catacombgl-043-supporting-all-catacomb-3d-games/?page=3&tab=comments#comment-2103497

**Comment by putridpete** [comment]
I'd like to throw in my support for this feature as well. I recently played this port using a CRT monitor, and a 320x200 resolution mode would have been the cherry on top for the retro experience with the convenience of modern controls I was going for.

**Comment by ArnoAnsems** [comment]
Support for the original 320x200 screen resolution was added in version 0.5.0.
