### ISSUE TITLE
Binding Left Shift key to Run keeps getting unbound

### ISSUE THREAD

**Issue by vermian** [ArnoAnsems/CatacombGL#54]
If I bind the Left Shift key to Run, it works, but subsequent game starts reset this key binding. It seems like in the CatacombGL.ini key bindings, "Right Shift=Run" is automatically added, and "Left Shift=Run" keeps getting deleted. If I set the CatacombGL.ini file as Read-only with "Left Shift=Run" only, it works as a workaround.
Using CatacombGL-Windows-64bit-0-5-4 with Windows 10 x64.

**Comment by ArnoAnsems** [comment]
Thank you for reporting this issue!
I've reproduced it and will look into a fix.

**Comment by ArnoAnsems** [comment]
This issue is solved in version 0.5.5.
