### ISSUE TITLE
Add Armageddon and Apocalypse non GOG games

### ISSUE THREAD

**Issue by raptus84** [ArnoAnsems/CatacombGL#57]
Hi,
is it possibile to play also the adventure non-gog trilogy games? I mean the dos originals.
Is it in the to-do list?
thanks

**Comment by ArnoAnsems** [comment]
Hello,
I appreciate your interest, but unfortunately at this moment I'm not planning to support every game version.
For the record, the games shipped via the GOG Catacombs Pack are also DOS-based; they're just launched via DOSBox to make them run on Windows.

In the near future I would like to add support for Catacomb Abyss v1.12, which is an older shareware version.
As far as I know, that would leave the following game versions as unsupported by CatacombGL:
- Catacomb 3-D v1.00 (the original Gamer's Edge version, where the bad guy is called Grelminar and Nemesis is the one to be rescued)
- Curse of the Catacombs (original retail release of Catacomb Armageddon by Froggman)
- Terror of the Catacombs (original retail release of Catacomb Apocalypse by Froggman)

Those three are game versions that are neither freely distributed as shareware, nor sold commercially as part of the Catacombs Pack. Which means the only way to obtain them is to buy a very expensive second-hand physical copy on EBay, or to download them from a potentially unsafe abandonware site. While I can understand a desire for completeness, I don't want to encourage CatacombGL users to get their game data in such a way. So unless these versions get officially added to the Catacombs Pack or some other commercial package, I will not add support for them to CatacombGL. I hope you'll understand.

**Comment by raptus84** [comment]
I've got them from an abandonware site actually. I respect your opinion but I think it's a bit too much for a software that is 33 years old... I know that principles and passion are important (I'm a dev too) but if you'll complete the compatibility it could help making those games more accessible to everyone.
I don't think those old games could help some devs to survive (ID software developers are rich and others are old too, they've made their moment).
I hope you'll change your mind in the future.
Regards
